# Generated by Django 4.2.3 on 2023-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employement',
            new_name='Employment',
        ),
        migrations.AlterField(
            model_name='company',
            name='departments',
            field=models.ManyToManyField(blank=True, to='app.department'),
        ),
    ]
