# Generated by Django 4.2.3 on 2023-07-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_employement_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=32),
        ),
    ]
